import { onMounted, ref } from 'vue'
import { defineStore } from 'pinia'

export const useTrainingCard = defineStore('training', () => {
  const menuItems = ref([
    {
      id: 1,
      employee: 'Olukayode Benson',
      department: 'Marketing',
      month: 'January 2025',
      topic: 'Ad Strategy',
      outcome: 'Certified Campaign Planner',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-01-15',
      evidence: 'Attached',
      rating: 5,
    },
    {
      id: 2,
      employee: 'Mariam Thompson',
      department: 'Finance',
      month: 'February 2025',
      topic: 'Tax Auditing',
      outcome: 'Senior Auditor Specialist',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'On going',
      dueDate: '2025-02-20',
      evidence: 'Attached',
      rating: 3,
    },
    {
      id: 3,
      employee: 'Chidi Richardson',
      department: 'IT Support',
      month: 'January 2025',
      topic: 'Cloud Ops',
      outcome: 'Azure Infrastructure Lead',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Not started',
      dueDate: '2025-01-28',
      evidence: 'Attached',
      rating: 2,
    },
    {
      id: 4,
      employee: 'Fatima Al-Sayed',
      department: 'Design',
      month: 'February 2025',
      topic: 'UI Patterns',
      outcome: 'Advanced Product Designer',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-02-12',
      evidence: 'Attached',
      rating: 4,
    },
    {
      id: 5,
      employee: 'Anthony McGeorge',
      department: 'Sales',
      month: 'January 2025',
      topic: 'CRM Mastery',
      outcome: 'Lead Pipeline Manager',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'On going',
      dueDate: '2025-01-30',
      evidence: 'Attached',
      rating: 5,
    },
    {
      id: 6,
      employee: "Grace O'Connell",
      department: 'HR Dept',
      month: 'February 2025',
      topic: 'Hiring Flow',
      outcome: 'Strategic Talent Recruiter',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-02-25',
      evidence: 'Attached',
      rating: 4,
    },
    {
      id: 7,
      employee: 'Samuel Hendrick',
      department: 'Legal',
      month: 'January 2025',
      topic: 'IP Law 101',
      outcome: 'Intellectual Property Expert',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Not started',
      dueDate: '2025-01-10',
      evidence: 'Attached',
      rating: 1,
    },
    {
      id: 8,
      employee: 'Isabella Knight',
      department: 'Security',
      month: 'February 2025',
      topic: 'Cyber Shield',
      outcome: 'Security Systems Analyst',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'On going',
      dueDate: '2025-02-28',
      evidence: 'Attached',
      rating: 3,
    },
    {
      id: 9,
      employee: 'Bernardo Silva',
      department: 'Logistics',
      month: 'January 2025',
      topic: 'Fleet Mgmt',
      outcome: 'Supply Chain Coordinator',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-01-22',
      evidence: 'Attached',
      rating: 5,
    },
    {
      id: 10,
      employee: 'Amina Abdullah',
      department: 'Writing',
      month: 'February 2025',
      topic: 'SEO Copy',
      outcome: 'Certified Content Strategist',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'Not started',
      dueDate: '2025-02-05',
      evidence: 'Attached',
      rating: 2,
    },
    {
      id: 11,
      employee: 'Christopher Ray',
      department: 'Admin',
      month: 'January 2025',
      topic: 'Data Entry',
      outcome: 'Efficient Operations Clerk',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'On going',
      dueDate: '2025-01-18',
      evidence: 'Attached',
      rating: 4,
    },
    {
      id: 12,
      employee: 'Victoria Prince',
      department: 'Customer',
      month: 'February 2025',
      topic: 'Conflict Res',
      outcome: 'Lead Support Specialist',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-02-14',
      evidence: 'Attached',
      rating: 5,
    },
    {
      id: 13,
      employee: 'Jonathan Webber',
      department: 'R & D',
      month: 'January 2025',
      topic: 'Lab Safety',
      outcome: 'Qualified Safety Officer',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Not started',
      dueDate: '2025-01-31',
      evidence: 'Attached',
      rating: 3,
    },
    {
      id: 14,
      employee: 'Elizabeth Moore',
      department: 'Editorial',
      month: 'February 2025',
      topic: 'Style Guide',
      outcome: 'Professional Senior Editor',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'On going',
      dueDate: '2025-02-10',
      evidence: 'Attached',
      rating: 4,
    },
    {
      id: 15,
      employee: 'Benjamin Franklin',
      department: 'Billing',
      month: 'January 2025',
      topic: 'Invoicing',
      outcome: 'Accounts Payable Manager',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-01-05',
      evidence: 'Attached',
      rating: 1,
    },
  ])
  const setRating = (task, newRating) => {
    task.rating = newRating
  }
  const selectedId = ref(null)
  const activeGoal = ref(null)
  const indexing = ref(null)
  const handleSubmit = (line, index, filtering) => {
    activeGoal.value = line
    selectedId.value = line.id
    indexing.value = index
    // console.log(index)
  }
  // landing page
  // onMounted(() => {
  //   const retrieveData = localStorage.getItem('myList')
  //   if (retrieveData) {
  //     goal.value = JSON.parse(retrieveData)
  //   }
  // })
  const goal = ref({
    career_goals: [
      {
        id: '1',
        goal: 'Improve content writing skill',
        completion_date: '12/10/2023',
        status: 'On going',
        feedback: 'Satisfactory',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
        department: 'Customer service',
        level: 'user',
        timeline: 'short',
      },
      {
        id: '2',
        goal: 'Obtain AWS Cloud Cert',
        completion_date: '15/01/2024',
        status: 'Not Started',
        feedback: 'N/A',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
        department: 'IT',
        level: 'IT',
        timeline: 'mid',
      },
      {
        id: '3',
        goal: 'Master Public Speaking',
        completion_date: '20/11/2023',
        status: 'On going',
        feedback: 'Improving',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
        department: 'operation',
        level: 'manager',
        timeline: 'long',
      },
      {
        id: '4',
        goal: 'Learn Python Automation',
        completion_date: '01/02/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'IT',
        level: 'IT',
        timeline: 'short',
      },
      {
        id: '5',
        goal: 'Emotional Intelligence Training',
        completion_date: '30/12/2023',
        status: 'On going',
        feedback: 'Positive',
        department: 'finance',
        level: 'manager',
        timeline: 'mid',
      },
      {
        id: '6',
        goal: 'Strategic Planning Workshop',
        completion_date: '15/03/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'operation',
        level: 'HOD',
        timeline: 'short',
      },
      {
        id: '7',
        goal: 'Advanced Excel Cert',
        completion_date: '10/11/2023',
        status: 'Completed',
        feedback: 'Excellent',
        department: 'finance',
        level: 'user',
        timeline: 'long',
      },
      {
        id: '8',
        goal: 'SQL for Data Analysis',
        completion_date: '25/01/2025',
        status: 'On going',
        feedback: 'Steady',
        department: 'IT',
        level: 'knowledge manager',
        timeline: 'mid',
      },
      {
        id: '9',
        goal: 'Leadership Foundation Course',
        completion_date: '14/04/2025',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'Customer service',
        level: 'manager',
        timeline: 'short',
      },
      {
        id: '10',
        goal: 'Time Management Mastery',
        completion_date: '05/12/2023',
        status: 'Completed',
        feedback: 'Good',
        department: 'operation',
        level: 'user',
        timeline: 'mid',
      },
      {
        id: '11',
        goal: 'Negotiation Skills Training',
        completion_date: '18/02/2026',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'finance',
        level: 'manager',
        timeline: 'long',
      },
      {
        id: '12',
        goal: 'Project Management Prof.',
        completion_date: '22/05/2026',
        status: 'On going',
        feedback: 'On track',
        department: 'operation',
        level: 'HOD',
        timeline: 'short',
      },
      {
        id: '13',
        goal: 'Business Ethics Seminar',
        completion_date: '09/11/2023',
        status: 'Completed',
        feedback: 'Satisfactory',
        department: 'finance',
        level: 'user',
        timeline: 'mid',
      },
      {
        id: '14',
        goal: 'Financial Literacy for Managers',
        completion_date: '30/03/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'finance',
        level: 'manager',
        timeline: 'long',
      },
      {
        id: '15',
        goal: 'Conflict Resolution Cert',
        completion_date: '12/01/2024',
        status: 'On going',
        feedback: 'Good',
        department: 'Customer service',
        level: 'knowledge manager',
        timeline: 'mid',
      },
      {
        id: '16',
        goal: 'Technical Documentation Skill',
        completion_date: '05/04/2025',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'IT',
        level: 'IT',
        timeline: 'short',
      },
      {
        id: '17',
        goal: 'Global Team Collaboration',
        completion_date: '20/12/2023',
        status: 'On going',
        feedback: 'Positive',
        department: 'operation',
        level: 'manager',
        timeline: 'mid',
      },
      {
        id: '18',
        goal: 'Market Research Basics',
        completion_date: '15/02/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'Customer service',
        level: 'user',
        timeline: 'long',
      },
      {
        id: '19',
        goal: 'Sales Prospecting Mastery',
        completion_date: '10/05/2026',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'Customer service',
        level: 'user',
        timeline: 'short',
      },
      {
        id: '20',
        goal: 'Cybersecurity Awareness',
        completion_date: '01/11/2023',
        status: 'Completed',
        feedback: 'Excellent',
        department: 'IT',
        level: 'user',
        timeline: 'mid',
      },
      {
        id: '21',
        goal: 'CRM Software Proficiency',
        completion_date: '15/03/2024',
        status: 'On going',
        feedback: 'Steady',
        department: 'Customer service',
        level: 'knowledge manager',
        timeline: 'short',
      },
      {
        id: '22',
        goal: 'Brand Voice Development',
        completion_date: '28/02/2026',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'operation',
        level: 'manager',
        timeline: 'long',
      },
      {
        id: '23',
        goal: 'Data Privacy Compliance',
        completion_date: '10/12/2023',
        status: 'Completed',
        feedback: 'Satisfactory',
        department: 'IT',
        level: 'HOD',
        timeline: 'mid',
      },
      {
        id: '24',
        goal: 'Change Management Training',
        completion_date: '20/04/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'operation',
        level: 'manager',
        timeline: 'short',
      },
    ],
    areas_of_interest: [
      {
        id: '25',
        goal: 'Master Data Visualization',
        completion_date: '05/01/2024',
        status: 'Not Started',
        feedback: 'N/A',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
        department: 'finance',
        level: 'knowledge manager',
        timeline: 'mid',
      },
      {
        id: '26',
        goal: 'Explore UX Research',
        completion_date: '14/02/2024',
        status: 'Not Started',
        feedback: 'N/A',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
        department: 'IT',
        level: 'user',
        timeline: 'long',
      },
      {
        id: '27',
        goal: 'Blockchain Basics',
        completion_date: '12/12/2023',
        status: 'On going',
        feedback: 'Good',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
        department: 'IT',
        level: 'IT',
        timeline: 'short',
      },
      {
        id: '28',
        goal: 'Figma for Prototyping',
        completion_date: '10/01/2024',
        status: 'On going',
        feedback: 'Satisfactory',
        department: 'IT',
        level: 'user',
        timeline: 'mid',
      },
      {
        id: '29',
        goal: 'Behavioral Economics',
        completion_date: '20/03/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'finance',
        level: 'knowledge manager',
        timeline: 'long',
      },
      {
        id: '30',
        goal: 'Agile Methodologies',
        completion_date: '05/11/2023',
        status: 'Completed',
        feedback: 'Strong',
        department: 'operation',
        level: 'manager',
        timeline: 'short',
      },
      {
        id: '31',
        goal: 'Generative AI Art',
        completion_date: '30/11/2023',
        status: 'On going',
        feedback: 'N/A',
        department: 'IT',
        level: 'user',
        timeline: 'mid',
      },
      {
        id: '32',
        goal: 'Financial Modeling',
        completion_date: '15/04/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'finance',
        level: 'manager',
        timeline: 'short',
      },
      {
        id: '33',
        goal: 'Mobile App Design',
        completion_date: '12/05/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'IT',
        level: 'user',
        timeline: 'long',
      },
      {
        id: '34',
        goal: 'Cloud Computing Trends',
        completion_date: '01/01/2024',
        status: 'On going',
        feedback: 'Good',
        department: 'IT',
        level: 'IT',
        timeline: 'mid',
      },
      {
        id: '35',
        goal: 'Digital Marketing Strategy',
        completion_date: '15/02/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'Customer service',
        level: 'manager',
        timeline: 'short',
      },
      {
        id: '36',
        goal: 'Social Media Algorithms',
        completion_date: '20/11/2023',
        status: 'Completed',
        feedback: 'Great',
        department: 'Customer service',
        level: 'knowledge manager',
        timeline: 'long',
      },
      {
        id: '37',
        goal: 'VR/AR Development',
        completion_date: '30/06/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'IT',
        level: 'IT',
        timeline: 'mid',
      },
      {
        id: '38',
        goal: 'Sustainable Engineering',
        completion_date: '15/03/2024',
        status: 'On going',
        feedback: 'Satisfactory',
        department: 'operation',
        level: 'knowledge manager',
        timeline: 'short',
      },
      {
        id: '39',
        goal: 'Neuroscience in Marketing',
        completion_date: '10/04/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'Customer service',
        level: 'user',
        timeline: 'mid',
      },
      {
        id: '40',
        goal: 'API Economy Concepts',
        completion_date: '05/01/2024',
        status: 'On going',
        feedback: 'Positive',
        department: 'IT',
        level: 'IT',
        timeline: 'long',
      },
      {
        id: '41',
        goal: 'Ethical Hacking Basics',
        completion_date: '22/02/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'IT',
        level: 'IT',
        timeline: 'short',
      },
      {
        id: '42',
        goal: 'Microservices Architecture',
        completion_date: '15/05/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'IT',
        level: 'IT',
        timeline: 'mid',
      },
      {
        id: '43',
        goal: 'Game Design Fundamentals',
        completion_date: '01/03/2024',
        status: 'On going',
        feedback: 'Good',
        department: 'IT',
        level: 'user',
        timeline: 'long',
      },
      {
        id: '44',
        goal: 'Voice User Interface',
        completion_date: '12/12/2023',
        status: 'Completed',
        feedback: 'Excellent',
        department: 'IT',
        level: 'knowledge manager',
        timeline: 'short',
      },
      {
        id: '45',
        goal: 'Bioinformatics Intro',
        completion_date: '30/04/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'IT',
        level: 'user',
        timeline: 'mid',
      },
      {
        id: '46',
        goal: 'Quantum Computing 101',
        completion_date: '20/06/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'IT',
        level: 'knowledge manager',
        timeline: 'long',
      },
      {
        id: '47',
        goal: 'E-commerce Optimization',
        completion_date: '15/11/2023',
        status: 'Completed',
        feedback: 'Good',
        department: 'Customer service',
        level: 'manager',
        timeline: 'short',
      },
    ],
    mentorship: [
      {
        id: '48',
        goal: 'Find Senior Design Mentor',
        completion_date: '15/12/2023',
        status: 'Completed',
        feedback: 'Satisfactory',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
        department: 'IT',
        level: 'user',
        timeline: 'mid',
      },
      {
        id: '49',
        goal: 'Mentor Junior Copywriter',
        completion_date: '01/05/2024',
        status: 'On going',
        feedback: 'Positive',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
        department: 'Customer service',
        level: 'manager',
        timeline: 'long',
      },
      {
        id: '50',
        goal: 'Shadow Project Manager',
        completion_date: '15/11/2023',
        status: 'On going',
        feedback: 'Great',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
        department: 'operation',
        level: 'user',
        timeline: 'short',
      },
      {
        id: '51',
        goal: 'Industry Leader Interview',
        completion_date: '10/01/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'operation',
        level: 'HOD',
        timeline: 'mid',
      },
      {
        id: '52',
        goal: 'Peer Mentorship Program',
        completion_date: '01/12/2023',
        status: 'Completed',
        feedback: 'Helpful',
        department: 'Customer service',
        level: 'user',
        timeline: 'long',
      },
      {
        id: '53',
        goal: 'Executive Shadowing',
        completion_date: '30/06/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'operation',
        level: 'manager',
        timeline: 'short',
      },
      {
        id: '54',
        goal: 'Code Review Volunteering',
        completion_date: '15/02/2024',
        status: 'On going',
        feedback: 'Helpful',
        department: 'IT',
        level: 'IT',
        timeline: 'mid',
      },
      {
        id: '55',
        goal: 'Reverse Mentorship Session',
        completion_date: '20/12/2023',
        status: 'On going',
        feedback: 'Insightful',
        department: 'finance',
        level: 'knowledge manager',
        timeline: 'long',
      },
      {
        id: '56',
        goal: 'Community Tech Mentoring',
        completion_date: '01/04/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'IT',
        level: 'IT',
        timeline: 'short',
      },
      {
        id: '57',
        goal: 'Internal Growth Coaching',
        completion_date: '10/11/2023',
        status: 'Completed',
        feedback: 'Excellent',
        department: 'Customer service',
        level: 'HOD',
        timeline: 'mid',
      },
      {
        id: '58',
        goal: 'Diversity Advocacy Mentoring',
        completion_date: '15/03/2024',
        status: 'On going',
        feedback: 'Strong',
        department: 'operation',
        level: 'manager',
        timeline: 'long',
      },
      {
        id: '59',
        goal: 'UX Portfolio Feedback',
        completion_date: '05/02/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'IT',
        level: 'user',
        timeline: 'short',
      },
      {
        id: '60',
        goal: 'Public Relations Mentorship',
        completion_date: '12/12/2023',
        status: 'Completed',
        feedback: 'Good',
        department: 'Customer service',
        level: 'manager',
        timeline: 'mid',
      },
      {
        id: '61',
        goal: 'Sales Strategy Coaching',
        completion_date: '22/04/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'Customer service',
        level: 'manager',
        timeline: 'long',
      },
      {
        id: '62',
        goal: 'Product Roadmap Review',
        completion_date: '15/01/2024',
        status: 'On going',
        feedback: 'Positive',
        department: 'operation',
        level: 'HOD',
        timeline: 'short',
      },
      {
        id: '63',
        goal: 'Agile Coaching',
        completion_date: '01/03/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'operation',
        level: 'knowledge manager',
        timeline: 'mid',
      },
      {
        id: '64',
        goal: 'Resume Review Session',
        completion_date: '10/11/2023',
        status: 'Completed',
        feedback: 'Useful',
        department: 'finance',
        level: 'user',
        timeline: 'long',
      },
      {
        id: '65',
        goal: 'Startup Founder Mentoring',
        completion_date: '30/05/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'operation',
        level: 'HOD',
        timeline: 'short',
      },
      {
        id: '66',
        goal: 'Data Science Mentorship',
        completion_date: '20/02/2024',
        status: 'On going',
        feedback: 'Steady',
        department: 'IT',
        level: 'IT',
        timeline: 'mid',
      },
      {
        id: '67',
        goal: 'Creative Direction Advice',
        completion_date: '15/12/2023',
        status: 'Completed',
        feedback: 'Satisfactory',
        department: 'operation',
        level: 'manager',
        timeline: 'long',
      },
      {
        id: '68',
        goal: 'Networking Skills Coaching',
        completion_date: '05/04/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'Customer service',
        level: 'user',
        timeline: 'short',
      },
      {
        id: '69',
        goal: 'HR Policy Mentorship',
        completion_date: '12/03/2024',
        status: 'On going',
        feedback: 'Good',
        department: 'operation',
        level: 'knowledge manager',
        timeline: 'mid',
      },
      {
        id: '70',
        goal: 'Cross-Functional Leadership',
        completion_date: '25/06/2024',
        status: 'Not Started',
        feedback: 'N/A',
        department: 'operation',
        level: 'HOD',
        timeline: 'long',
      },
    ],
  })
  // skills assessment
  const skill = ref([
    {
      id: 1,
      name: 'Public Speaking',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Satisfactory',
      date: '15/01/2024',
      department: 'IT',
      level: 'User',
    },
    {
      id: 2,
      name: 'Public Speaking',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Satisfactory',
      date: '22/01/2024',
      department: 'Finance',
      level: 'Manager',
    },
    {
      id: 3,
      name: 'Public Speaking',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '05/02/2024',
      department: 'Accounting',
      level: 'IT',
    },
    {
      id: 4,
      name: 'Public Speaking',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Satisfactory',
      date: '12/02/2024',
      department: 'Operation',
      level: 'HOD',
    },
    {
      id: 5,
      name: 'Public Speaking',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Satisfactory',
      date: '28/02/2024',
      department: 'Customer service',
      level: 'Knowledge Manager',
    },
    {
      id: 6,
      name: 'Public Speaking',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '10/03/2024',
      department: 'IT',
      level: 'User',
    },
    {
      id: 7,
      name: 'Public Speaking',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Satisfactory',
      date: '25/03/2024',
      department: 'Finance',
      level: 'IT',
    },
    {
      id: 8,
      name: 'Public Speaking',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Satisfactory',
      date: '04/04/2024',
      department: 'Accounting',
      level: 'Manager',
    },
    {
      id: 9,
      name: 'Public Speaking',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '18/04/2024',
      department: 'Operation',
      level: 'Knowledge Manager',
    },
    {
      id: 10,
      name: 'Public Speaking',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Satisfactory',
      date: '30/04/2024',
      department: 'Customer service',
      level: 'HOD',
    },
    {
      id: 11,
      name: 'Public Speaking',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Satisfactory',
      date: '12/05/2024',
      department: 'IT',
      level: 'User',
    },
    {
      id: 12,
      name: 'Public Speaking',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '22/05/2024',
      department: 'Finance',
      level: 'IT',
    },
    {
      id: 13,
      name: 'Project Management',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Excellent',
      date: '05/06/2024',
      department: 'Accounting',
      level: 'Manager',
    },
    {
      id: 14,
      name: 'Project Management',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Good',
      date: '19/06/2024',
      department: 'Operation',
      level: 'Knowledge Manager',
    },
    {
      id: 15,
      name: 'Data Analysis',
      current_state: 'Beginner',
      desired_state: 'Intermediate',
      status: 'Not started',
      feedback: 'Pending',
      date: '02/07/2024',
      department: 'Customer service',
      level: 'User',
    },
    {
      id: 16,
      name: 'Data Analysis',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Satisfactory',
      date: '15/07/2024',
      department: 'IT',
      level: 'IT',
    },
    {
      id: 17,
      name: 'Leadership',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Outstanding',
      date: '30/07/2024',
      department: 'Finance',
      level: 'HOD',
    },
    {
      id: 18,
      name: 'Leadership',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '14/08/2024',
      department: 'Accounting',
      level: 'Manager',
    },
    {
      id: 19,
      name: 'Technical Writing',
      current_state: 'Beginner',
      desired_state: 'Intermediate',
      status: 'On going',
      feedback: 'Good',
      date: '28/08/2024',
      department: 'Operation',
      level: 'User',
    },
    {
      id: 20,
      name: 'Technical Writing',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Satisfactory',
      date: '10/09/2024',
      department: 'Customer service',
      level: 'Knowledge Manager',
    },
    {
      id: 21,
      name: 'Public Speaking',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Satisfactory',
      date: '24/09/2024',
      department: 'IT',
      level: 'IT',
    },
    {
      id: 22,
      name: 'Public Speaking',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Excellent',
      date: '08/10/2024',
      department: 'Finance',
      level: 'HOD',
    },
    {
      id: 23,
      name: 'Project Management',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '22/10/2024',
      department: 'Accounting',
      level: 'Manager',
    },
    {
      id: 24,
      name: 'Project Management',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Good',
      date: '05/11/2024',
      department: 'Operation',
      level: 'User',
    },
    {
      id: 25,
      name: 'Data Analysis',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Satisfactory',
      date: '19/11/2024',
      department: 'Customer service',
      level: 'Knowledge Manager',
    },
    {
      id: 26,
      name: 'Data Analysis',
      current_state: 'Beginner',
      desired_state: 'Intermediate',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '03/12/2024',
      department: 'IT',
      level: 'IT',
    },
    {
      id: 27,
      name: 'Leadership',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Good',
      date: '17/12/2024',
      department: 'Finance',
      level: 'Manager',
    },
    {
      id: 28,
      name: 'Leadership',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Satisfactory',
      date: '31/12/2024',
      department: 'Accounting',
      level: 'HOD',
    },
    {
      id: 29,
      name: 'Negotiation',
      current_state: 'Beginner',
      desired_state: 'Intermediate',
      status: 'On going',
      feedback: 'Satisfactory',
      date: '14/01/2025',
      department: 'Operation',
      level: 'User',
    },
    {
      id: 30,
      name: 'Negotiation',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Excellent',
      date: '28/01/2025',
      department: 'Customer service',
      level: 'Manager',
    },
    {
      id: 31,
      name: 'Public Speaking',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '11/02/2025',
      department: 'IT',
      level: 'IT',
    },
    {
      id: 32,
      name: 'Public Speaking',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Good',
      date: '25/02/2025',
      department: 'Finance',
      level: 'Knowledge Manager',
    },
    {
      id: 33,
      name: 'Project Management',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Satisfactory',
      date: '11/03/2025',
      department: 'Accounting',
      level: 'Manager',
    },
    {
      id: 34,
      name: 'Project Management',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Satisfactory',
      date: '25/03/2025',
      department: 'Operation',
      level: 'HOD',
    },
    {
      id: 35,
      name: 'Data Analysis',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '08/04/2025',
      department: 'Customer service',
      level: 'User',
    },
    {
      id: 36,
      name: 'Data Analysis',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Excellent',
      date: '22/04/2025',
      department: 'IT',
      level: 'IT',
    },
    {
      id: 37,
      name: 'Leadership',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Good',
      date: '06/05/2025',
      department: 'Finance',
      level: 'Knowledge Manager',
    },
    {
      id: 38,
      name: 'Leadership',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '20/05/2025',
      department: 'Accounting',
      level: 'Manager',
    },
    {
      id: 39,
      name: 'Critical Thinking',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Satisfactory',
      date: '03/06/2025',
      department: 'Operation',
      level: 'HOD',
    },
    {
      id: 40,
      name: 'Critical Thinking',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Good',
      date: '17/06/2025',
      department: 'Customer service',
      level: 'User',
    },
    {
      id: 41,
      name: 'Public Speaking',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Satisfactory',
      date: '01/07/2025',
      department: 'IT',
      level: 'Manager',
    },
    {
      id: 42,
      name: 'Public Speaking',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '15/07/2025',
      department: 'Finance',
      level: 'IT',
    },
    {
      id: 43,
      name: 'Project Management',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Excellent',
      date: '29/07/2025',
      department: 'Accounting',
      level: 'Knowledge Manager',
    },
    {
      id: 44,
      name: 'Project Management',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Satisfactory',
      date: '12/08/2025',
      department: 'Operation',
      level: 'HOD',
    },
    {
      id: 45,
      name: 'Data Analysis',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Good',
      date: '26/08/2025',
      department: 'Customer service',
      level: 'User',
    },
    {
      id: 46,
      name: 'Data Analysis',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '09/09/2025',
      department: 'IT',
      level: 'Manager',
    },
    {
      id: 47,
      name: 'Leadership',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Satisfactory',
      date: '23/09/2025',
      department: 'Finance',
      level: 'IT',
    },
    {
      id: 48,
      name: 'Leadership',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Excellent',
      date: '07/10/2025',
      department: 'Accounting',
      level: 'HOD',
    },
    {
      id: 49,
      name: 'Problem Solving',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '21/10/2025',
      department: 'Operation',
      level: 'Knowledge Manager',
    },
    {
      id: 50,
      name: 'Problem Solving',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Good',
      date: '04/11/2025',
      department: 'Customer service',
      level: 'User',
    },
    {
      id: 51,
      name: 'Public Speaking',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Satisfactory',
      date: '11/11/2025',
      department: 'IT',
      level: 'IT',
    },
    {
      id: 52,
      name: 'Public Speaking',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Satisfactory',
      date: '18/11/2025',
      department: 'Finance',
      level: 'Manager',
    },
    {
      id: 53,
      name: 'Project Management',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '25/11/2025',
      department: 'Accounting',
      level: 'User',
    },
    {
      id: 54,
      name: 'Project Management',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Good',
      date: '02/12/2025',
      department: 'Operation',
      level: 'HOD',
    },
    {
      id: 55,
      name: 'Data Analysis',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Excellent',
      date: '03/12/2025',
      department: 'Customer service',
      level: 'Knowledge Manager',
    },
    {
      id: 56,
      name: 'Data Analysis',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '04/12/2025',
      department: 'IT',
      level: 'Manager',
    },
    {
      id: 57,
      name: 'Leadership',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Satisfactory',
      date: '05/12/2025',
      department: 'Finance',
      level: 'IT',
    },
    {
      id: 58,
      name: 'Leadership',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Good',
      date: '08/12/2025',
      department: 'Accounting',
      level: 'HOD',
    },
    {
      id: 59,
      name: 'Time Management',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Satisfactory',
      date: '10/12/2025',
      department: 'Operation',
      level: 'User',
    },
    {
      id: 60,
      name: 'Time Management',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Satisfactory',
      date: '12/12/2025',
      department: 'Customer service',
      level: 'Knowledge Manager',
    },
    {
      id: 61,
      name: 'Public Speaking',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '14/12/2025',
      department: 'IT',
      level: 'IT',
    },
    {
      id: 62,
      name: 'Public Speaking',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Excellent',
      date: '16/12/2025',
      department: 'Finance',
      level: 'Manager',
    },
    {
      id: 63,
      name: 'Project Management',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Satisfactory',
      date: '18/12/2025',
      department: 'Accounting',
      level: 'User',
    },
    {
      id: 64,
      name: 'Project Management',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Good',
      date: '20/12/2025',
      department: 'Operation',
      level: 'HOD',
    },
    {
      id: 65,
      name: 'Data Analysis',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Satisfactory',
      date: '22/12/2025',
      department: 'Customer service',
      level: 'Knowledge Manager',
    },
    {
      id: 66,
      name: 'Data Analysis',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Satisfactory',
      date: '24/12/2025',
      department: 'IT',
      level: 'Manager',
    },
    {
      id: 67,
      name: 'Leadership',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Not started',
      feedback: 'Satisfactory',
      date: '26/12/2025',
      department: 'Finance',
      level: 'IT',
    },
    {
      id: 68,
      name: 'Leadership',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Good',
      date: '28/12/2025',
      department: 'Accounting',
      level: 'HOD',
    },
    {
      id: 69,
      name: 'Emotional Intelligence',
      current_state: 'Beginner',
      desired_state: 'Expert',
      status: 'Completed',
      feedback: 'Excellent',
      date: '30/12/2025',
      department: 'Operation',
      level: 'Knowledge Manager',
    },
    {
      id: 70,
      name: 'Emotional Intelligence',
      current_state: 'Intermediate',
      desired_state: 'Expert',
      status: 'On going',
      feedback: 'Satisfactory',
      date: '31/12/2025',
      department: 'Customer service',
      level: 'User',
    },
  ])
  const tableColumns = [
    { key: 'id', label: 'S/N', size: 'flex-[0_0_10%]' },
    { key: 'name', label: 'Skills', size: 'flex-[0_0_20%]' },
    { key: 'current_state', label: 'Current State', size: 'flex-[0_0_15%]' },
    { key: 'desired_state', label: 'Desired State', size: 'flex-[0_0_15%]' },
    { key: 'status', label: 'Status', size: 'flex-[0_0_15%]' },
    { key: 'feedback', label: 'Feedback', size: 'flex-[0_0_25%]' },
  ]
  const addItems = async (item, type, selected = null) => {
    if (type === 'development') {
      goal.value[selected].push(item)
      localStorage.setItem('myList', JSON.stringify(goal.value))
      console.log(goal.value)
    } else if (type === 'assessment') {
      skill.value.push(item)
    }
  }
  const deleteItems = (selected, id, filtering) => {
    const getFilter = filtering === '' ? 'career_goals' : filtering
    if (id === 'landing') {
      goal.value[getFilter].splice(selected, 1)
    } else if (id === 'assessment') {
      skill.value.splice(selected, 1)
    }
  }
  // function to choose between Q1, Q2, Q3, Q4
  const handleQuarterType = (dateString) => {
    const [day, month, year] = dateString.split('/').map(Number)
    const date = new Date(year, month - 1, day)
    if (isNaN(date)) {
      throw new Error('in correct date')
    }
    const calcQuarter = Math.floor(date.getMonth() / 3) + 1
    if (!year && !calcQuarter) return
    return { calcQuarter, year }
  }
  // function to edit the goals
  const editingId = ref(null)
  const editBuffer = ref({})
  const startEditing = (item) => {
    editingId.value = item.id
    editBuffer.value = { ...item }
    console.log(editBuffer.value)
  }
  const cancelEdit = () => {
    editingId.value = null
  }
  // function to calculate the graph parameters
  const getPercentage = (dataArray) => {
    if (!Array.isArray(dataArray)) {
      throw new Error('error')
    }
    const data = dataArray
    const counts = data.reduce(
      (acc, item) => {
        const status = item.status.toLowerCase()
        if (status === 'not started') acc.notStarted++
        if (status === 'completed') acc.completed++
        if (status === 'on going') acc.onGoing++
        return acc
      },
      { completed: 0, notStarted: 0, onGoing: 0 },
    )
    const total = counts.completed + counts.onGoing + counts.notStarted
    // console.log(total)
    return {
      completed: Math.round((counts.completed * 100) / total),
      ongoing: Math.round((counts.onGoing * 100) / total),
      notstarted: Math.round((counts.notStarted * 100) / total),
    }
  }
  return {
    menuItems,
    setRating,
    selectedId,
    activeGoal,
    indexing,
    handleSubmit,
    goal,
    skill,
    tableColumns,
    addItems,
    deleteItems,
    handleQuarterType,
    editBuffer,
    editingId,
    startEditing,
    cancelEdit,
    getPercentage,
  }
})
