import { ref } from 'vue'
import { defineStore } from 'pinia'

export const useTrainingCard = defineStore('training', () => {
  const menuItems = ref([
    {
      id: 1,
      employee: 'Olukayode Benson',
      department: 'Marketing',
      month: 'January 2025',
      topic: 'Ad Strategy',
      outcome: 'Certified Campaign Planner',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-01-15',
      evidence: 'Attached',
      rating: 5,
    },
    {
      id: 2,
      employee: 'Mariam Thompson',
      department: 'Finance',
      month: 'February 2025',
      topic: 'Tax Auditing',
      outcome: 'Senior Auditor Specialist',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'On going',
      dueDate: '2025-02-20',
      evidence: 'Attached',
      rating: 3,
    },
    {
      id: 3,
      employee: 'Chidi Richardson',
      department: 'IT Support',
      month: 'January 2025',
      topic: 'Cloud Ops',
      outcome: 'Azure Infrastructure Lead',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Not started',
      dueDate: '2025-01-28',
      evidence: 'Attached',
      rating: 2,
    },
    {
      id: 4,
      employee: 'Fatima Al-Sayed',
      department: 'Design',
      month: 'February 2025',
      topic: 'UI Patterns',
      outcome: 'Advanced Product Designer',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-02-12',
      evidence: 'Attached',
      rating: 4,
    },
    {
      id: 5,
      employee: 'Anthony McGeorge',
      department: 'Sales',
      month: 'January 2025',
      topic: 'CRM Mastery',
      outcome: 'Lead Pipeline Manager',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'On going',
      dueDate: '2025-01-30',
      evidence: 'Attached',
      rating: 5,
    },
    {
      id: 6,
      employee: "Grace O'Connell",
      department: 'HR Dept',
      month: 'February 2025',
      topic: 'Hiring Flow',
      outcome: 'Strategic Talent Recruiter',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-02-25',
      evidence: 'Attached',
      rating: 4,
    },
    {
      id: 7,
      employee: 'Samuel Hendrick',
      department: 'Legal',
      month: 'January 2025',
      topic: 'IP Law 101',
      outcome: 'Intellectual Property Expert',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Not started',
      dueDate: '2025-01-10',
      evidence: 'Attached',
      rating: 1,
    },
    {
      id: 8,
      employee: 'Isabella Knight',
      department: 'Security',
      month: 'February 2025',
      topic: 'Cyber Shield',
      outcome: 'Security Systems Analyst',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'On going',
      dueDate: '2025-02-28',
      evidence: 'Attached',
      rating: 3,
    },
    {
      id: 9,
      employee: 'Bernardo Silva',
      department: 'Logistics',
      month: 'January 2025',
      topic: 'Fleet Mgmt',
      outcome: 'Supply Chain Coordinator',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-01-22',
      evidence: 'Attached',
      rating: 5,
    },
    {
      id: 10,
      employee: 'Amina Abdullah',
      department: 'Writing',
      month: 'February 2025',
      topic: 'SEO Copy',
      outcome: 'Certified Content Strategist',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'Not started',
      dueDate: '2025-02-05',
      evidence: 'Attached',
      rating: 2,
    },
    {
      id: 11,
      employee: 'Christopher Ray',
      department: 'Admin',
      month: 'January 2025',
      topic: 'Data Entry',
      outcome: 'Efficient Operations Clerk',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'On going',
      dueDate: '2025-01-18',
      evidence: 'Attached',
      rating: 4,
    },
    {
      id: 12,
      employee: 'Victoria Prince',
      department: 'Customer',
      month: 'February 2025',
      topic: 'Conflict Res',
      outcome: 'Lead Support Specialist',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-02-14',
      evidence: 'Attached',
      rating: 5,
    },
    {
      id: 13,
      employee: 'Jonathan Webber',
      department: 'R & D',
      month: 'January 2025',
      topic: 'Lab Safety',
      outcome: 'Qualified Safety Officer',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Not started',
      dueDate: '2025-01-31',
      evidence: 'Attached',
      rating: 3,
    },
    {
      id: 14,
      employee: 'Elizabeth Moore',
      department: 'Editorial',
      month: 'February 2025',
      topic: 'Style Guide',
      outcome: 'Professional Senior Editor',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'On going',
      dueDate: '2025-02-10',
      evidence: 'Attached',
      rating: 4,
    },
    {
      id: 15,
      employee: 'Benjamin Franklin',
      department: 'Billing',
      month: 'January 2025',
      topic: 'Invoicing',
      outcome: 'Accounts Payable Manager',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-01-05',
      evidence: 'Attached',
      rating: 1,
    },
  ])
  const setRating = (task, newRating) => {
    task.rating = newRating
  }
  const selectedId = ref(null)
  const activeGoal = ref(null)
  const indexing = ref(null)
  const handleSubmit = (line, index, filtering) => {
    activeGoal.value = line
    selectedId.value = line.id || line.id[0].num
    indexing.value = index
    console.log(index)
  }
  // landing page
  const goal = ref({
    career_goals: [
      {
        id: '1',
        goal: 'Improve content writing skill',
        completion_date: '12/10/2023',
        status: 'On going',
        feedback: 'Satisfactory',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
      },
      {
        id: '2',
        goal: 'Obtain AWS Cloud Cert',
        completion_date: '15/01/2024',
        status: 'Not Started',
        feedback: 'N/A',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
      },
      {
        id: '3',
        goal: 'Master Public Speaking',
        completion_date: '20/11/2023',
        status: 'On going',
        feedback: 'Improving',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
      },
      {
        id: '4',
        goal: 'Learn Python Automation',
        completion_date: '01/02/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '5',
        goal: 'Emotional Intelligence Training',
        completion_date: '30/12/2023',
        status: 'On going',
        feedback: 'Positive',
      },
      {
        id: '6',
        goal: 'Strategic Planning Workshop',
        completion_date: '15/03/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '7',
        goal: 'Advanced Excel Cert',
        completion_date: '10/11/2023',
        status: 'Completed',
        feedback: 'Excellent',
      },
      {
        id: '8',
        goal: 'SQL for Data Analysis',
        completion_date: '25/01/2024',
        status: 'On going',
        feedback: 'Steady',
      },
      {
        id: '9',
        goal: 'Leadership Foundation Course',
        completion_date: '14/04/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '10',
        goal: 'Time Management Mastery',
        completion_date: '05/12/2023',
        status: 'Completed',
        feedback: 'Good',
      },
      {
        id: '11',
        goal: 'Negotiation Skills Training',
        completion_date: '18/02/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '12',
        goal: 'Project Management Prof.',
        completion_date: '22/05/2024',
        status: 'On going',
        feedback: 'On track',
      },
      {
        id: '13',
        goal: 'Business Ethics Seminar',
        completion_date: '09/11/2023',
        status: 'Completed',
        feedback: 'Satisfactory',
      },
      {
        id: '14',
        goal: 'Financial Literacy for Managers',
        completion_date: '30/03/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '15',
        goal: 'Conflict Resolution Cert',
        completion_date: '12/01/2024',
        status: 'On going',
        feedback: 'Good',
      },
      {
        id: '16',
        goal: 'Technical Documentation Skill',
        completion_date: '05/04/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '17',
        goal: 'Global Team Collaboration',
        completion_date: '20/12/2023',
        status: 'On going',
        feedback: 'Positive',
      },
      {
        id: '18',
        goal: 'Market Research Basics',
        completion_date: '15/02/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '19',
        goal: 'Sales Prospecting Mastery',
        completion_date: '10/05/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '20',
        goal: 'Cybersecurity Awareness',
        completion_date: '01/11/2023',
        status: 'Completed',
        feedback: 'Excellent',
      },
      {
        id: '21',
        goal: 'CRM Software Proficiency',
        completion_date: '15/03/2024',
        status: 'On going',
        feedback: 'Steady',
      },
      {
        id: '22',
        goal: 'Brand Voice Development',
        completion_date: '28/02/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '23',
        goal: 'Data Privacy Compliance',
        completion_date: '10/12/2023',
        status: 'Completed',
        feedback: 'Satisfactory',
      },
      {
        id: '24',
        goal: 'Change Management Training',
        completion_date: '20/04/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
    ],
    areas_of_interest: [
      {
        id: '25',
        goal: 'Master Data Visualization',
        completion_date: '05/01/2024',
        status: 'Not Started',
        feedback: 'N/A',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
      },
      {
        id: '26',
        goal: 'Explore UX Research',
        completion_date: '14/02/2024',
        status: 'Not Started',
        feedback: 'N/A',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
      },
      {
        id: '27',
        goal: 'Blockchain Basics',
        completion_date: '12/12/2023',
        status: 'On going',
        feedback: 'Good',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
      },
      {
        id: '28',
        goal: 'Figma for Prototyping',
        completion_date: '10/01/2024',
        status: 'On going',
        feedback: 'Satisfactory',
      },
      {
        id: '29',
        goal: 'Behavioral Economics',
        completion_date: '20/03/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '30',
        goal: 'Agile Methodologies',
        completion_date: '05/11/2023',
        status: 'Completed',
        feedback: 'Strong',
      },
      {
        id: '31',
        goal: 'Generative AI Art',
        completion_date: '30/11/2023',
        status: 'On going',
        feedback: 'N/A',
      },
      {
        id: '32',
        goal: 'Financial Modeling',
        completion_date: '15/04/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '33',
        goal: 'Mobile App Design',
        completion_date: '12/05/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '34',
        goal: 'Cloud Computing Trends',
        completion_date: '01/01/2024',
        status: 'On going',
        feedback: 'Good',
      },
      {
        id: '35',
        goal: 'Digital Marketing Strategy',
        completion_date: '15/02/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '36',
        goal: 'Social Media Algorithms',
        completion_date: '20/11/2023',
        status: 'Completed',
        feedback: 'Great',
      },
      {
        id: '37',
        goal: 'VR/AR Development',
        completion_date: '30/06/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '38',
        goal: 'Sustainable Engineering',
        completion_date: '15/03/2024',
        status: 'On going',
        feedback: 'Satisfactory',
      },
      {
        id: '39',
        goal: 'Neuroscience in Marketing',
        completion_date: '10/04/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '40',
        goal: 'API Economy Concepts',
        completion_date: '05/01/2024',
        status: 'On going',
        feedback: 'Positive',
      },
      {
        id: '41',
        goal: 'Ethical Hacking Basics',
        completion_date: '22/02/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '42',
        goal: 'Microservices Architecture',
        completion_date: '15/05/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '43',
        goal: 'Game Design Fundamentals',
        completion_date: '01/03/2024',
        status: 'On going',
        feedback: 'Good',
      },
      {
        id: '44',
        goal: 'Voice User Interface',
        completion_date: '12/12/2023',
        status: 'Completed',
        feedback: 'Excellent',
      },
      {
        id: '45',
        goal: 'Bioinformatics Intro',
        completion_date: '30/04/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '46',
        goal: 'Quantum Computing 101',
        completion_date: '20/06/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '47',
        goal: 'E-commerce Optimization',
        completion_date: '15/11/2023',
        status: 'Completed',
        feedback: 'Good',
      },
    ],
    mentorship: [
      {
        id: '48',
        goal: 'Find Senior Design Mentor',
        completion_date: '15/12/2023',
        status: 'Completed',
        feedback: 'Satisfactory',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
      },
      {
        id: '49',
        goal: 'Mentor Junior Copywriter',
        completion_date: '01/05/2024',
        status: 'On going',
        feedback: 'Positive',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
      },
      {
        id: '50',
        goal: 'Shadow Project Manager',
        completion_date: '15/11/2023',
        status: 'On going',
        feedback: 'Great',
        work_rate: 'Work',
        challenges: 'Lack of Mentorship',
      },
      {
        id: '51',
        goal: 'Industry Leader Interview',
        completion_date: '10/01/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '52',
        goal: 'Peer Mentorship Program',
        completion_date: '01/12/2023',
        status: 'Completed',
        feedback: 'Helpful',
      },
      {
        id: '53',
        goal: 'Executive Shadowing',
        completion_date: '30/06/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '54',
        goal: 'Code Review Volunteering',
        completion_date: '15/02/2024',
        status: 'On going',
        feedback: 'Helpful',
      },
      {
        id: '55',
        goal: 'Reverse Mentorship Session',
        completion_date: '20/12/2023',
        status: 'On going',
        feedback: 'Insightful',
      },
      {
        id: '56',
        goal: 'Community Tech Mentoring',
        completion_date: '01/04/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '57',
        goal: 'Internal Growth Coaching',
        completion_date: '10/11/2023',
        status: 'Completed',
        feedback: 'Excellent',
      },
      {
        id: '58',
        goal: 'Diversity Advocacy Mentoring',
        completion_date: '15/03/2024',
        status: 'On going',
        feedback: 'Strong',
      },
      {
        id: '59',
        goal: 'UX Portfolio Feedback',
        completion_date: '05/02/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '60',
        goal: 'Public Relations Mentorship',
        completion_date: '12/12/2023',
        status: 'Completed',
        feedback: 'Good',
      },
      {
        id: '61',
        goal: 'Sales Strategy Coaching',
        completion_date: '22/04/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '62',
        goal: 'Product Roadmap Review',
        completion_date: '15/01/2024',
        status: 'On going',
        feedback: 'Positive',
      },
      {
        id: '63',
        goal: 'Agile Coaching',
        completion_date: '01/03/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '64',
        goal: 'Resume Review Session',
        completion_date: '10/11/2023',
        status: 'Completed',
        feedback: 'Useful',
      },
      {
        id: '65',
        goal: 'Startup Founder Mentoring',
        completion_date: '30/05/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '66',
        goal: 'Data Science Mentorship',
        completion_date: '20/02/2024',
        status: 'On going',
        feedback: 'Steady',
      },
      {
        id: '67',
        goal: 'Creative Direction Advice',
        completion_date: '15/12/2023',
        status: 'Completed',
        feedback: 'Satisfactory',
      },
      {
        id: '68',
        goal: 'Networking Skills Coaching',
        completion_date: '05/04/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
      {
        id: '69',
        goal: 'HR Policy Mentorship',
        completion_date: '12/03/2024',
        status: 'On going',
        feedback: 'Good',
      },
      {
        id: '70',
        goal: 'Cross-Functional Leadership',
        completion_date: '25/06/2024',
        status: 'Not Started',
        feedback: 'N/A',
      },
    ],
  })
  // skills assessment
  const skill = ref([
    {
      id: [{ num: 1, size: 'flex-[0_0_10%]' }],
      skill: [{ num: 'Public Speaking', size: 'flex-[0_0_20%]' }],
      current_state: [{ num: 'Begineer', size: 'flex-[0_0_15%]' }],
      desired_state: [{ num: 'Expert', size: 'flex-[0_0_15%]' }],
      status: [{ num: 'On going', size: 'flex-[0_0_15%]' }],
      feedback: [{ num: 'satisfactory', size: 'flex-[0_0_15%]' }],
    },
    {
      id: [{ num: 2, size: 'flex-[0_0_10%]' }],
      skill: [{ num: 'Public Speaking', size: 'flex-[0_0_20%]' }],
      current_state: [{ num: 'Intermediate', size: 'flex-[0_0_15%]' }],
      desired_state: [{ num: 'Expert', size: 'flex-[0_0_15%]' }],
      status: [{ num: 'Completed', size: 'flex-[0_0_15%]' }],
      feedback: [{ num: 'Satisfactory', size: 'flex-[0_0_15%]' }],
    },
    {
      id: [{ num: 3, size: 'flex-[0_0_10%]' }],
      skill: [{ num: 'Public Speaking', size: 'flex-[0_0_20%]' }],
      current_state: [{ num: 'Beginner', size: 'flex-[0_0_15%]' }],
      desired_state: [{ num: 'Expert', size: 'flex-[0_0_15%]' }],
      status: [{ num: 'Not started', size: 'flex-[0_0_15%]' }],
      feedback: [{ num: 'Satisfactory', size: 'flex-[0_0_15%]' }],
    },
    {
      id: [{ num: 4, size: 'flex-[0_0_10%]' }],
      skill: [{ num: 'Public Speaking', size: 'flex-[0_0_20%]' }],
      current_state: [{ num: 'Intermediate', size: 'flex-[0_0_15%]' }],
      desired_state: [{ num: 'Expert', size: 'flex-[0_0_15%]' }],
      status: [{ num: 'On going', size: 'flex-[0_0_15%]' }],
      feedback: [{ num: 'Satisfactory', size: 'flex-[0_0_15%]' }],
    },
    {
      id: [{ num: 5, size: 'flex-[0_0_10%]' }],
      skill: [{ num: 'Public Speaking', size: 'flex-[0_0_20%]' }],
      current_state: [{ num: 'Beginner', size: 'flex-[0_0_15%]' }],
      desired_state: [{ num: 'Expert', size: 'flex-[0_0_15%]' }],
      status: [{ num: 'Completed', size: 'flex-[0_0_15%]' }],
      feedback: [{ num: 'Satisfactory', size: 'flex-[0_0_15%]' }],
    },
    {
      id: [{ num: 6, size: 'flex-[0_0_10%]' }],
      skill: [{ num: 'Public Speaking', size: 'flex-[0_0_20%]' }],
      current_state: [{ num: 'Intermediate', size: 'flex-[0_0_15%]' }],
      desired_state: [{ num: 'Expert', size: 'flex-[0_0_15%]' }],
      status: [{ num: 'Not started', size: 'flex-[0_0_15%]' }],
      feedback: [{ num: 'Satisfactory', size: 'flex-[0_0_15%]' }],
    },
    {
      id: [{ num: 7, size: 'flex-[0_0_10%]' }],
      skill: [{ num: 'Public Speaking', size: 'flex-[0_0_20%]' }],
      current_state: [{ num: 'Beginner', size: 'flex-[0_0_15%]' }],
      desired_state: [{ num: 'Expert', size: 'flex-[0_0_15%]' }],
      status: [{ num: 'On going', size: 'flex-[0_0_15%]' }],
      feedback: [{ num: 'Satisfactory', size: 'flex-[0_0_15%]' }],
    },
    {
      id: [{ num: 8, size: 'flex-[0_0_10%]' }],
      skill: [{ num: 'Public Speaking', size: 'flex-[0_0_20%]' }],
      current_state: [{ num: 'Intermediate', size: 'flex-[0_0_15%]' }],
      desired_state: [{ num: 'Expert', size: 'flex-[0_0_15%]' }],
      status: [{ num: 'Completed', size: 'flex-[0_0_15%]' }],
      feedback: [{ num: 'Satisfactory', size: 'flex-[0_0_15%]' }],
    },
    {
      id: [{ num: 9, size: 'flex-[0_0_10%]' }],
      skill: [{ num: 'Public Speaking', size: 'flex-[0_0_20%]' }],
      current_state: [{ num: 'Beginner', size: 'flex-[0_0_15%]' }],
      desired_state: [{ num: 'Expert', size: 'flex-[0_0_15%]' }],
      status: [{ num: 'Not started', size: 'flex-[0_0_15%]' }],
      feedback: [{ num: 'Satisfactory', size: 'flex-[0_0_15%]' }],
    },
    {
      id: [{ num: 10, size: 'flex-[0_0_10%]' }],
      skill: [{ num: 'Public Speaking', size: 'flex-[0_0_20%]' }],
      current_state: [{ num: 'Intermediate', size: 'flex-[0_0_15%]' }],
      desired_state: [{ num: 'Expert', size: 'flex-[0_0_15%]' }],
      status: [{ num: 'On going', size: 'flex-[0_0_15%]' }],
      feedback: [{ num: 'Satisfactory', size: 'flex-[0_0_15%]' }],
    },
    {
      id: [{ num: 11, size: 'flex-[0_0_10%]' }],
      skill: [{ num: 'Public Speaking', size: 'flex-[0_0_20%]' }],
      current_state: [{ num: 'Beginner', size: 'flex-[0_0_15%]' }],
      desired_state: [{ num: 'Expert', size: 'flex-[0_0_15%]' }],
      status: [{ num: 'Completed', size: 'flex-[0_0_15%]' }],
      feedback: [{ num: 'Satisfactory', size: 'flex-[0_0_15%]' }],
    },
    {
      id: [{ num: 12, size: 'flex-[0_0_10%]' }],
      skill: [{ num: 'Public Speaking', size: 'flex-[0_0_20%]' }],
      current_state: [{ num: 'Intermediate', size: 'flex-[0_0_15%]' }],
      desired_state: [{ num: 'Expert', size: 'flex-[0_0_15%]' }],
      status: [{ num: 'Not started', size: 'flex-[0_0_15%]' }],
      feedback: [{ num: 'Satisfactory', size: 'flex-[0_0_15%]' }],
    },
  ])
  const addItems = (item, selected) => {
    goal.value[selected].push(item)
  }
  const deleteItems = (selected, filtering) => {
    // console.log(skill)
    // console.log(skill.value)
    return goal.value[filtering].splice(selected, 1) || skill.value.splice(selected, 1)
    // console.log(goal2.value)
  }
  return {
    menuItems,
    setRating,
    selectedId,
    activeGoal,
    indexing,
    handleSubmit,
    goal,
    skill,
    addItems,
    deleteItems,
  }
})
