import { ref } from 'vue'
import { defineStore } from 'pinia'

export const useTrainingCard = defineStore('training', () => {
  const menuItems = ref([
    {
      id: 1,
      employee: 'Olukayode Benson',
      department: 'Marketing',
      month: 'January 2025',
      topic: 'Ad Strategy',
      outcome: 'Certified Campaign Planner',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-01-15',
      evidence: 'Attached',
      rating: 5,
    },
    {
      id: 2,
      employee: 'Mariam Thompson',
      department: 'Finance',
      month: 'February 2025',
      topic: 'Tax Auditing',
      outcome: 'Senior Auditor Specialist',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'On going',
      dueDate: '2025-02-20',
      evidence: 'Attached',
      rating: 3,
    },
    {
      id: 3,
      employee: 'Chidi Richardson',
      department: 'IT Support',
      month: 'January 2025',
      topic: 'Cloud Ops',
      outcome: 'Azure Infrastructure Lead',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Not started',
      dueDate: '2025-01-28',
      evidence: 'Attached',
      rating: 2,
    },
    {
      id: 4,
      employee: 'Fatima Al-Sayed',
      department: 'Design',
      month: 'February 2025',
      topic: 'UI Patterns',
      outcome: 'Advanced Product Designer',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-02-12',
      evidence: 'Attached',
      rating: 4,
    },
    {
      id: 5,
      employee: 'Anthony McGeorge',
      department: 'Sales',
      month: 'January 2025',
      topic: 'CRM Mastery',
      outcome: 'Lead Pipeline Manager',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'On going',
      dueDate: '2025-01-30',
      evidence: 'Attached',
      rating: 5,
    },
    {
      id: 6,
      employee: "Grace O'Connell",
      department: 'HR Dept',
      month: 'February 2025',
      topic: 'Hiring Flow',
      outcome: 'Strategic Talent Recruiter',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-02-25',
      evidence: 'Attached',
      rating: 4,
    },
    {
      id: 7,
      employee: 'Samuel Hendrick',
      department: 'Legal',
      month: 'January 2025',
      topic: 'IP Law 101',
      outcome: 'Intellectual Property Expert',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Not started',
      dueDate: '2025-01-10',
      evidence: 'Attached',
      rating: 1,
    },
    {
      id: 8,
      employee: 'Isabella Knight',
      department: 'Security',
      month: 'February 2025',
      topic: 'Cyber Shield',
      outcome: 'Security Systems Analyst',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'On going',
      dueDate: '2025-02-28',
      evidence: 'Attached',
      rating: 3,
    },
    {
      id: 9,
      employee: 'Bernardo Silva',
      department: 'Logistics',
      month: 'January 2025',
      topic: 'Fleet Mgmt',
      outcome: 'Supply Chain Coordinator',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-01-22',
      evidence: 'Attached',
      rating: 5,
    },
    {
      id: 10,
      employee: 'Amina Abdullah',
      department: 'Writing',
      month: 'February 2025',
      topic: 'SEO Copy',
      outcome: 'Certified Content Strategist',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'Not started',
      dueDate: '2025-02-05',
      evidence: 'Attached',
      rating: 2,
    },
    {
      id: 11,
      employee: 'Christopher Ray',
      department: 'Admin',
      month: 'January 2025',
      topic: 'Data Entry',
      outcome: 'Efficient Operations Clerk',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'On going',
      dueDate: '2025-01-18',
      evidence: 'Attached',
      rating: 4,
    },
    {
      id: 12,
      employee: 'Victoria Prince',
      department: 'Customer',
      month: 'February 2025',
      topic: 'Conflict Res',
      outcome: 'Lead Support Specialist',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-02-14',
      evidence: 'Attached',
      rating: 5,
    },
    {
      id: 13,
      employee: 'Jonathan Webber',
      department: 'R & D',
      month: 'January 2025',
      topic: 'Lab Safety',
      outcome: 'Qualified Safety Officer',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Not started',
      dueDate: '2025-01-31',
      evidence: 'Attached',
      rating: 3,
    },
    {
      id: 14,
      employee: 'Elizabeth Moore',
      department: 'Editorial',
      month: 'February 2025',
      topic: 'Style Guide',
      outcome: 'Professional Senior Editor',
      method: 'Physical',
      skillsMapping: 'Proficiency',
      status: 'On going',
      dueDate: '2025-02-10',
      evidence: 'Attached',
      rating: 4,
    },
    {
      id: 15,
      employee: 'Benjamin Franklin',
      department: 'Billing',
      month: 'January 2025',
      topic: 'Invoicing',
      outcome: 'Accounts Payable Manager',
      method: 'Online',
      skillsMapping: 'Proficiency',
      status: 'Completed',
      dueDate: '2025-01-05',
      evidence: 'Attached',
      rating: 1,
    },
  ])
  const setRating = (task, newRating) => {
    task.rating = newRating
  }
  return {
    menuItems,
    setRating,
  }
})
